# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f6b70b9e1bca880016f261806fba94e7f4db1a3d8d8729b54b5c2d5b6ee4bd20611fd186af78d286139440329d7018a93f3e4a3f2f2486703040e92ae4dd5f72

test:
  secret_key_base: 192b9eeedb59f1582853c9750dd9cc889b0b5883e94a9c9e8b91d282c0b5218032e617f4dd6695bfbb536e1693deebb822109897cde06264c31e3abe7ed7cc77

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
